### ISSUE TITLE
Enter Absolute Image Path: 

### ISSUE THREAD

**Issue by qianyongsheng** [abhisharma7/PoseDetection#1]
Hi : 
   Is there an example?
Pose Estimation
Select:
 1:Image 
 2:Video 
 3:Webcam 
Choice(Number): 1
Enter Absolute Image Path:

**Comment by abhisharma7** [comment]
Hi,
So the program is for face pose estimation not entire human body. It takes three kind of input to detect face pose, it could take image, video or direct webcam.

As you selected image as choice, it is asking you the path of image which you want give as a input. Once its process that image it will create an output image with pose estimation(similar to an example shown in read me file of this repository).

I hope this answers your question. If you have any doubts in execution let me know.  
Abhishek

**Comment by abhisharma7** [comment]
I am closing this issue, as I don't think you have any follow up questions.
